version: '3'
services:
  redis:
    image: redis
    container_name: zjf-irc-redis
    restart: "no"
    volumes:
        - ./.docker-vol/redis/data:/data
    ports:
      - 6390:6379

  mysql8_arm64:
    # host network_mode only available for pure linux
    # network_mode: "host"
    image: arm64v8/mysql
    restart: "no"
    container_name: zjf-irc-mysql8-arm64
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    environment:
      MYSQL_ROOT_PASSWORD: h-Rz9)rkZ3H26~6Q@K?q
      MYSQL_DATABASE: zjf_irc_local
      MYSQL_USER: zjf_irc_user
      MYSQL_PASSWORD: nh*N:4H5;5>PmK3-pMk3
      TZ: Asia/Shanghai
    volumes:
      - ./.docker-vol/mysql8_arm64/db:/var/lib/mysql
    ports:
      - 13306:3306