/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Avatar: typeof import('./components/avatar/Avatar.vue')['default']
    Banner: typeof import('./components/banner/index.vue')['default']
    BaseTable: typeof import('./../../shared/components/base/table/BaseTable.vue')['default']
    Carousel: typeof import('./../../shared/components/cms/home/Carousel.vue')['default']
    Content: typeof import('./../../shared/components/cms/home/Content.vue')['default']
    Footer: typeof import('./../../shared/components/cms/home/Footer.vue')['default']
    HomeMenu: typeof import('./components/menu/HomeMenu.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    PlatformIntroduce: typeof import('./../../shared/components/cms/home/PlatformIntroduce.vue')['default']
    Question: typeof import('./../../shared/components/cms/question/Question.vue')['default']
    QuestionCard: typeof import('./components/card/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SMSInput: typeof import('./../../shared/components/input/SMSInput.vue')['default']
    Tabs: typeof import('./../../shared/components/base/tab/Tabs.vue')['default']
    UpdateDescribe: typeof import('./../../shared/components/cms/user/UpdateDescribe.vue')['default']
    ZBtn: typeof import('./../../shared/components/btn/ZBtn.vue')['default']
    ZDialog: typeof import('./../../shared/components/dialog/ZDialog.vue')['default']
    ZEmpty: typeof import('./components/empty/ZEmpty.vue')['default']
    ZExpansion: typeof import('./../../shared/components/expansion/ZExpansion.vue')['default']
    ZInput: typeof import('./../../shared/components/input/ZInput.vue')['default']
    ZLoading: typeof import('./../../shared/components/loading/ZLoading.vue')['default']
    ZMenu: typeof import('./../../shared/components/menu/ZMenu.vue')['default']
    ZMenu1: typeof import('./../../shared/components/menu/ZMenu1.vue')['default']
  }
}
