/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A0001: typeof import('./../../shared/components/cms/A0001.vue')['default']
    A0002: typeof import('./../../shared/components/cms/A0002.vue')['default']
    A0003: typeof import('./../../shared/components/cms/A0003.vue')['default']
    A0004: typeof import('./../../shared/components/cms/A0004.vue')['default']
    A0005: typeof import('./../../shared/components/cms/A0005.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Avatar: typeof import('./components/user/Avatar.vue')['default']
    Banner: typeof import('./components/banner/index.vue')['default']
    Carousel: typeof import('./../../shared/components/cms/home/Carousel.vue')['default']
    Content: typeof import('./../../shared/components/cms/home/Content.vue')['default']
    DesktopDoc: typeof import('./components/protocol/DesktopDoc.vue')['default']
    Empty: typeof import('./components/empty/index.vue')['default']
    ExportStatus: typeof import('./../../shared/components/status/ExportStatus.vue')['default']
    Footer: typeof import('./../../shared/components/cms/home/Footer.vue')['default']
    HomeMenu: typeof import('./components/menu/HomeMenu.vue')['default']
    LineEchartsCard: typeof import('./components/card/LineEchartsCard.vue')['default']
    PlatformIntroduce: typeof import('./../../shared/components/cms/home/PlatformIntroduce.vue')['default']
    PrivacyDoc: typeof import('./components/protocol/PrivacyDoc.vue')['default']
    Protocol: typeof import('./components/protocol/index.vue')['default']
    Question: typeof import('./../../shared/components/cms/question/Question.vue')['default']
    QuestionCard: typeof import('./components/card/QuestionCard.vue')['default']
    ReadonlyInput: typeof import('./../../shared/components/input/ReadonlyInput.vue')['default']
    RoundEchartsCard: typeof import('./components/card/RoundEchartsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SMSInput: typeof import('./../../shared/components/input/SMSInput.vue')['default']
    UploadDescribe: typeof import('./../../shared/components/cms/userCenter/UploadDescribe.vue')['default']
    UserAgreementDoc: typeof import('./components/protocol/UserAgreementDoc.vue')['default']
    VerifyStatus: typeof import('./components/user/VerifyStatus.vue')['default']
    WorksDoc: typeof import('./components/protocol/WorksDoc.vue')['default']
    ZBtn: typeof import('./../../shared/components/btn/ZBtn.vue')['default']
    ZBtnToggle: typeof import('./../../shared/components/btn/ZBtnToggle.vue')['default']
    ZChipSelect: typeof import('./../../shared/components/select/ZChipSelect.vue')['default']
    ZDialog: typeof import('./../../shared/components/dialog/ZDialog.vue')['default']
    ZDragUpload: typeof import('./../../shared/components/upload/ZDragUpload.vue')['default']
    ZExpansion: typeof import('./../../shared/components/expansion/ZExpansion.vue')['default']
    ZInput: typeof import('./../../shared/components/input/ZInput.vue')['default']
    ZLoading: typeof import('./../../shared/components/loading/ZLoading.vue')['default']
    ZMenu: typeof import('./../../shared/components/menu/ZMenu.vue')['default']
    ZMenu1: typeof import('./../../shared/components/menu/ZMenu1.vue')['default']
    ZSelect: typeof import('./../../shared/components/select/ZSelect.vue')['default']
    ZTable: typeof import('./../../shared/components/table/ZTable.vue')['default']
    ZUpload: typeof import('./../../shared/components/upload/ZUpload.vue')['default']
  }
}
