/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A0001: typeof import('./../../../shared/components/cms/A0001.vue')['default']
    A0002: typeof import('./../../../shared/components/cms/A0002.vue')['default']
    A0003: typeof import('./../../../shared/components/cms/A0003.vue')['default']
    A0004: typeof import('./../../../shared/components/cms/A0004.vue')['default']
    A0005: typeof import('./../../../shared/components/cms/A0005.vue')['default']
    A0006: typeof import('./../../../shared/components/cms/A0006.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppSidebar: typeof import('./../components/AppSidebar.vue')['default']
    CaptchaInput: typeof import('./../../../shared/components/input/CaptchaInput.vue')['default']
    ColorPicker: typeof import('./../components/color/ColorPicker.vue')['default']
    ComponentCard: typeof import('./../components/card/ComponentCard.vue')['default']
    Empty: typeof import('./../components/empty/index.vue')['default']
    ExportStatus: typeof import('./../../../shared/components/status/ExportStatus.vue')['default']
    HomeMenu: typeof import('./../components/menu/HomeMenu.vue')['default']
    List: typeof import('./../components/list/List.vue')['default']
    LogoutDialog: typeof import('./../../../shared/components/dialog/LogoutDialog.vue')['default']
    MenuItem: typeof import('./../components/menu/MenuItem.vue')['default']
    ReadonlyInput: typeof import('./../../../shared/components/input/ReadonlyInput.vue')['default']
    RichText: typeof import('./../components/richText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SMSInput: typeof import('./../../../shared/components/input/SMSInput.vue')['default']
    SubMenu: typeof import('./../components/menu/SubMenu.vue')['default']
    ZBtn: typeof import('./../../../shared/components/btn/ZBtn.vue')['default']
    ZBtnToggle: typeof import('./../../../shared/components/btn/ZBtnToggle.vue')['default']
    ZChipSelect: typeof import('./../../../shared/components/select/ZChipSelect.vue')['default']
    ZDialog: typeof import('./../../../shared/components/dialog/ZDialog.vue')['default']
    ZDragUpload: typeof import('./../../../shared/components/upload/ZDragUpload.vue')['default']
    ZExpansion: typeof import('./../../../shared/components/expansion/ZExpansion.vue')['default']
    ZInput: typeof import('./../../../shared/components/input/ZInput.vue')['default']
    ZLoading: typeof import('./../../../shared/components/loading/ZLoading.vue')['default']
    ZMenu: typeof import('./../../../shared/components/menu/ZMenu.vue')['default']
    ZSelect: typeof import('./../../../shared/components/select/ZSelect.vue')['default']
    ZTable: typeof import('./../components/table/ZTable.vue')['default']
    ZUpload: typeof import('./../../../shared/components/upload/ZUpload.vue')['default']
  }
}
